name: Build Android APK with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build cache
        uses: actions/cache@v3
        with:
          path: |
            .buildozer
            bin
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/*.py') }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer

      - name: Install dependencies
        run: |
          pip install --upgrade cython

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FaceApp-APK
          path: bin/*.apk
