name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip \
            git build-essential ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
            libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev libmtdev-dev xclip libjpeg-dev libfreetype6-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Accept Android SDK licenses manually
        run: |
          yes | sdkmanager --licenses || true
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: FaceApp-APK
          path: bin/*.apk
